
module.exports = {
    roles: require('./roles'),
    farmerDetails: require('./farmerDetails'),
    plotDetails: require('./plotDetails'),
    seasonDetails: require('./seasonDetails'),
    fertilizerApplications: require('./fertilizerApplications'),
    weeding: require('./weeding'),
    cropProtection: require('./cropProtection'),
    cropAttributes: require('./cropAttributes'),
    harvesting: require('./harvesting'),
    threshing: require('./threshing'),
    storage: require('./storage'),
    drying: require('./drying'),
    soilInformation: require('./soilInformation'),
    farmOperations: require('./farmOperations'),
    operationDates: require('./operationDates'),
    projects: require('./projects'),
    seedVarity: require('./seedVarity'),
    pratice: require('./pratice'),
    notification: require('./notification'),
    farmerFAQ: require('./farmerFAQ'),
    village: require('./village'),
    user: require('./user'),
    dataCollector: require('./dataCollector'),
    clients: require('./client'),
    dashBoard: require('./dashBoard'),
    categories: require('./categories'),
    dropdowns: require('./dropdowns'),
    state: require('./state'),
    district: require('./district'),
    block: require('./block'),
    crop: require('./crop'),
    cropType: require('./cropType'),
    intervention: require('./intervention'),
    transplanting: require('./transplanting'),
    sowing: require('./sowing'),
    seedDetails: require('./seedDetails'),
    irrigation: require('./irrigation'),
    waterManagement: require('./waterManagement'),
    machineTypes : require('./machineType'),
    machineBrands : require('./machineBrand'),
    fertilizer : require('./fertilizer'),
    seedTreatments : require('./seedtreatmentnames'),
    seedTreatmentTypes : require('./seedtreatmenttypes'),
    chemicalNames : require('./chemicals'),
    dcTransfer : require('./dctransfer'),
    amendments : require('./amendments'),
    irrigationFieldObservations : require('./irrigationFieldobservations'),   
}
